import {esc, first} from './utils.mjs';
import {getTheme} from './theme.mjs';

function normalizeArray(v){
  if(Array.isArray(v)) return v;
  if(!v) return [];
  return String(v).split(/[|;]/).map(s=>s.trim()).filter(Boolean);
}

export function renderLead(raw){
  const lead={...raw};
  const name=lead.business_name || lead.Business || lead.business || 'Local Business';
  const vertical=lead.preview_template || lead.Template || lead.vertical || lead.Vertical || 'Local Business';
  const city=lead.city || lead.City || '';
  const phone=lead.phone || lead.Phone || '';
  const rating=Number(lead.rating || lead.Rating || 0) || 0;
  const reviewsCount=Number(lead.review_count || lead.Reviews || 0) || 0;
  const observation=lead.verified_observation || lead['Preview Brief'] || lead.personalized_hook || lead['Personalized Hook'] || '';
  const services=normalizeArray(lead.services || lead.Services);
  const photos=normalizeArray(lead.photos || lead.Photos);
  const reviews=Array.isArray(lead.reviews) ? lead.reviews : [];
  const theme=getTheme(vertical, lead.cta || lead.CTA || '');
  const locationText=[city, lead.service_area].filter(Boolean).join(' • ');
  const socialProof = rating && reviewsCount ? `${rating.toFixed(1)} ★ · ${reviewsCount.toLocaleString()} public reviews` : rating ? `${rating.toFixed(1)} ★ rating` : '';
  const heroText = lead.hero || (city ? `${theme.hero} Serving ${city}.` : theme.hero);
  const ctaHref = phone ? `tel:${esc(phone.replace(/[^+\d]/g,''))}` : '#contact';
  const serviceCards=(services.length?services:['Core Service','Customer Support','Local Service']).slice(0,6).map((s,i)=>`<article class="card"><span>${String(i+1).padStart(2,'0')}</span><h3>${esc(s)}</h3><p>Clear, customer-friendly information for this service.</p></article>`).join('');
  const photoHtml=first(photos,3).map((p,i)=>`<img src="${esc(p)}" alt="${esc(name)} photo ${i+1}" loading="lazy">`).join('');
  const reviewHtml=first(reviews,3).map(r=>`<blockquote>“${esc(r.text||'')}”<footer>${esc(r.author||'Customer')}</footer></blockquote>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(name)} — Concept Preview</title><style>
  :root{--bg:#0b0d10;--panel:#14181d;--soft:#20262d;--text:#f6f7f9;--muted:#aeb7c2;--accent:#fff;--radius:22px}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--text);line-height:1.5}a{color:inherit;text-decoration:none}.wrap{width:min(1120px,92vw);margin:auto}.preview{position:sticky;top:0;z-index:10;background:#f7df72;color:#121212;text-align:center;padding:10px 16px;font-size:13px;font-weight:700;letter-spacing:.02em}.nav{display:flex;align-items:center;justify-content:space-between;padding:24px 0}.brand{font-weight:900;font-size:22px}.pill,.cta{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:13px 18px;font-weight:800}.pill{border:1px solid #2b323b}.cta{background:#fff;color:#111}.hero{padding:78px 0 54px}.eyebrow{font-size:12px;letter-spacing:.18em;color:#b7c0ca;font-weight:800}.hero h1{font-size:clamp(48px,8vw,98px);line-height:.95;letter-spacing:-.055em;max-width:950px;margin:18px 0 22px}.hero p{font-size:20px;color:var(--muted);max-width:720px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.proof{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px;color:#d8dde3}.proof b{background:var(--panel);padding:10px 14px;border-radius:999px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{background:var(--panel);padding:26px;border-radius:var(--radius);min-height:190px}.card span{color:#717b86;font-size:12px;font-weight:800}.card h3{font-size:24px;margin:30px 0 8px}.card p{color:var(--muted)}section{padding:56px 0}.sectionTitle{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:24px}.sectionTitle h2{font-size:42px;letter-spacing:-.04em;margin:0}.sectionTitle p{color:var(--muted);max-width:500px}.gallery{display:grid;grid-template-columns:2fr 1fr 1fr;gap:14px}.gallery img{width:100%;height:330px;object-fit:cover;border-radius:var(--radius)}.reviews{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.reviews blockquote{margin:0;background:var(--panel);padding:24px;border-radius:var(--radius);font-size:18px}.reviews footer{color:var(--muted);font-size:14px;margin-top:18px}.observation{background:#f4f6f8;color:#101216;padding:34px;border-radius:var(--radius)}.observation small{display:block;font-weight:900;letter-spacing:.12em;margin-bottom:8px}.contact{background:linear-gradient(135deg,#1d232a,#0f1216);border-radius:32px;padding:44px;display:flex;justify-content:space-between;gap:28px;align-items:center}.contact h2{font-size:42px;line-height:1;margin:0 0 12px}.contact p{color:var(--muted);margin:0}.footer{padding:38px 0 60px;color:#707984;font-size:13px}@media(max-width:760px){.grid,.reviews,.gallery{grid-template-columns:1fr}.gallery img{height:260px}.hero{padding-top:52px}.nav .pill{display:none}.contact{display:block}.contact .cta{margin-top:24px}.sectionTitle{display:block}}
  </style></head><body><div class="preview">CONCEPT PREVIEW — nothing on the business’s live website has been changed</div><main class="wrap"><nav class="nav"><div class="brand">${esc(name)}</div><a class="pill" href="${ctaHref}">${phone?esc(phone):esc(theme.cta)}</a></nav><header class="hero"><div class="eyebrow">${esc(theme.eyebrow)}</div><h1>${esc(heroText)}</h1><p>${esc(observation || `A mobile-first concept designed to make it easier for customers to understand the business and take the next step.`)}</p><div class="actions"><a class="cta" href="${ctaHref}">${esc(theme.cta)}</a><a class="pill" href="#services">Explore Services</a></div><div class="proof">${socialProof?`<b>${esc(socialProof)}</b>`:''}${locationText?`<b>${esc(locationText)}</b>`:''}</div></header><section id="services"><div class="sectionTitle"><h2>What customers need, upfront.</h2><p>Structured for clarity, trust and action on mobile.</p></div><div class="grid">${serviceCards}</div></section>${photoHtml?`<section><div class="sectionTitle"><h2>Real business. Better presentation.</h2></div><div class="gallery">${photoHtml}</div></section>`:''}${reviewHtml?`<section><div class="sectionTitle"><h2>Reputation that deserves to be seen.</h2></div><div class="reviews">${reviewHtml}</div></section>`:''}<section><div class="observation"><small>WHY THIS PREVIEW WAS BUILT</small><strong>${esc(observation || 'The business has a strong local presence that could be presented more clearly online.')}</strong></div></section><section><div class="contact" id="contact"><div><h2>Ready when your customer is.</h2><p>${esc(name)} · ${esc(city)}</p></div><a class="cta" href="${ctaHref}">${esc(theme.cta)}</a></div></section><footer class="footer">Concept preview prepared by Launchline Design. Business information shown should be verified before production launch.</footer></main></body></html>`;
}
